---
sudo: required

language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_841d42444d45_key -iv $encrypted_841d42444d45_iv -in molecule/default/clouds.yml.enc -out molecule/default/clouds.yml -d

install:
  - pip install -r test-requirements.txt

script:
  - tox

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
