---
- name: adminer - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  become: true
  with_items:
    - "{{ adminer_docker_compose_directory }}"

- name: adminer - copy docker-compose.yml file
  template:
    src: adminer/docker-compose.yml.j2
    dest: "{{ adminer_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: adminer - pull images
  command: "docker-compose -f {{ adminer_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: adminer - run service
  command: "docker-compose -f {{ adminer_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
