---
- name: cephclient - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ cephclient_configuration_directory }}"
    - "{{ cephclient_docker_compose_directory }}"

- name: cephclient - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: cephclient/ceph.conf.j2
      dest: "{{ cephclient_configuration_directory }}/ceph.conf"

- name: cephclient - copy keyring file
  copy:
    content: "{{ cephclient_keyring }}"
    dest: "{{ cephclient_configuration_directory }}/ceph.{{ cephclient_keyring_name }}.keyring"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: cephclient - copy docker-compose.yml file
  template:
    src: cephclient/docker-compose.yml.j2
    dest: "{{ cephclient_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: cephclient - run service
  docker_service:
    project_name: cephclient
    project_src: "{{ cephclient_docker_compose_directory }}"
    pull: yes

- name: cephclient - copy wrapper scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - ceph
    - rbd
  become: true
