# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_helper }}"

- name: Include ara-server tasks
  include: ara-server.yml
  tags: ara-server
  when: configure_ara_server|bool

- name: Include helper tasks
  include: helper.yml
  tags: helper 
  when: configure_helper|bool

- name: Include phpmyadmin tasks
  include: phpmyadmin.yml
  tags: phpmyadmin
  when: configure_phpmyadmin|bool

- name: Include aptly tasks
  include: aptly.yml
  tags: aptly
  when: configure_aptly|bool

- name: Include registry tasks
  include: registry.yml
  tags: registry
  when: configure_aptly|bool
