---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_helper }}"

- name: Include ceph-dash tasks
  include: ceph-dash.yml
  tags: ceph-dash
  when: configure_ceph_dash|bool

- name: Include phpmyadmin tasks
  include: phpmyadmin.yml
  tags: phpmyadmin
  when: configure_phpmyadmin|bool

- name: Include openstackclient tasks
  include: openstackclient.yml
  tags: openstackclient
  when: configure_openstackclient|bool

- name: Include rally tasks
  include: rally.yml
  tags: rally
  when: configure_rally|bool
