---
- name: openstackclient - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ openstackclient_configuration_directory }}"
    - "{{ openstackclient_docker_compose_directory }}"

- name: openstackclient - copy docker-compose.yml file
  template:
    src: openstackclient/docker-compose.yml.j2
    dest: "{{ openstackclient_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: openstackclient - run service
  docker_service:
    project_name: openstackclient
    project_src: "{{ openstackclient_docker_compose_directory }}"
    pull: yes

- name: openstackclient - copy wrapper scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - openstack
  become: true
