---
- name: phpmyadmin - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  become: true
  with_items:
    - "{{ phpmyadmin_docker_compose_directory }}"

- name: phpmyadmin - copy docker-compose.yml file
  template:
    src: phpmyadmin/docker-compose.yml.j2
    dest: "{{ phpmyadmin_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: phpmyadmin - run service
  command: "docker-compose -f {{ phpmyadmin_docker_compose_directory }}/docker-compose.yml -p phpmyadmin create --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
