---
- name: phpmyadmin - run service
  docker_service:
    project_name: phpmyadmin
    definition:
      version: '2'
      services:
        phpmyadmin:
          restart: unless-stopped
          image: "{{ phpmyadmin_image }}"
          environment:
            PMA_HOST: "{{ phpmyadmin_database_host }}"
          ports:
            - "{{ phpmyadmin_host }}:{{ phpmyadmin_port }}:80"
          volumes:
            - "/etc/hosts:/etc/hosts:ro"
