---
- name: rally - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  become: true
  with_items:
    - "{{ rally_configuration_directory }}"
    - "{{ rally_docker_compose_directory }}"
    - "{{ rally_tests_directory }}"

- name: rally - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: rally/rally.conf.j2
      dest: "{{ rally_configuration_directory }}/rally.conf"
    - src: rally/nginx.conf.j2
      dest: "{{ rally_configuration_directory }}/nginx.conf"

- name: rally - copy docker-compose.yml file
  template:
    src: rally/docker-compose.yml.j2
    dest: "{{ rally_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: rally - run service
  docker_service:
    project_name: rally
    project_src: "{{ rally_docker_compose_directory }}"
    pull: yes

- name: rally - copy wrapper scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - rally
  become: true
