---
- name: rally - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  become: true
  with_items:
    - "{{ rally_configuration_directory }}"
    - "{{ rally_docker_compose_directory }}"
    - "{{ rally_tests_directory }}"

- name: rally - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: rally/rally.conf.j2
      dest: "{{ rally_configuration_directory }}/rally.conf"
    - src: rally/nginx.conf.j2
      dest: "{{ rally_configuration_directory }}/nginx.conf"

- name: rally - copy docker-compose.yml file
  template:
    src: rally/docker-compose.yml.j2
    dest: "{{ rally_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: rally - pull images
  command: "docker-compose -f {{ rally_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: rally - run service
  command: "docker-compose -f {{ rally_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)

- name: rally - copy wrapper scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - rally
  become: true
